
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"E:\Tkinter-Designer-master\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1280x720")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 720,
    width = 1280,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    640.0,
    360.0,
    image=image_image_1
)

canvas.create_rectangle(
    0.0,
    457.0,
    1280.0,
    782.0,
    fill="#09979D",
    outline="")

canvas.create_rectangle(
    256.0,
    81.06157105211878,
    950.9999728881904,
    576.2764278472241,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    256.0,
    57.0,
    951.0,
    133.0,
    fill="#09979D",
    outline="")

canvas.create_text(
    443.0,
    71.0,
    anchor="nw",
    text="PESANAN ANDA",
    fill="#FFFFFF",
    font=("Inter Bold", 40 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_49.png"))
button_49 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_49 clicked"),
    relief="flat"
)
button_49.place(
    x=298.0,
    y=390.0,
    width=618.0,
    height=67.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_50.png"))
button_50 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_50 clicked"),
    relief="flat"
)
button_50.place(
    x=298.0,
    y=218.0,
    width=610.0,
    height=72.0
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    92.0,
    74.0,
    image=image_image_2
)
window.resizable(False, False)
window.mainloop()
